from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .integrated_nodes import NODE_CLASS_MAPPINGS as INTEGRATED_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as INTEGRATED_DISPLAY_MAPPINGS

# Merge mappings
NODE_CLASS_MAPPINGS.update(INTEGRATED_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(INTEGRATED_DISPLAY_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
